### ISSUE TITLE
Add a `r10k:install` task

### ISSUE THREAD

**Issue by joshuaspence** [voxpupuli/ra10ke#2]
It would be great if this gem provided an `r10k:install` task which could be used to install modules using `r10k`.

**Comment by james-powis** [comment]
I am curious why this would be desired? r10k deploy environment -pv already does this...

**Comment by tampakrap** [comment]
I believe the request is to be able to add a new gem in the Puppetfile through a rake task command. If that's the case, I honestly have no idea how to implement it, and I'm not sure if it is even worth the trouble to do it

**Comment by electrofelix** [comment]
My initial rudimentary local hack to do this:

```
namespace :r10k do
  task :install do
    require 'r10k/puppetfile'
    require 'puppet_forge'

    puppetfile_dir = File.expand_path(File.join(__FILE__, '..'))
    modules_dir = File.join(puppetfile_dir, 'puppet/r10k')
    puppetfile = R10K::Puppetfile.new(puppetfile_dir, modules_dir)
    puppetfile.load!
    puppetfile.modules.each do |mod|
      mod.sync
    end
  end
end

# prepending r10k task to prep
task :spec_prep => ['r10k:install']
```

There is probably a nicer way to do this using the R10k.Action.Puppetfile.Install object instead at https://github.com/puppetlabs/r10k/blob/master/lib/r10k/action/puppetfile/install.rb but this seemed to be close enough.

Eventually settled for a slightly more complex piece of code because I wanted to be able to install the modules under a path sometimes just to be working with them, and for a full spec test to get a separate set instead of linking to them via fixtures.

```
namespace :r10k do
  r10k_spec_modpath = File.expand_path(File.join(__FILE__, '..', 'spec/fixtures/modules/r10k'))
  r10k_default_modpath = File.expand_path(File.join(__FILE__, '..', 'puppet/r10k'))
  task :spec_install do
    Rake::Task['r10k:install'].invoke(r10k_spec_modpath)
  end

  task :install, [:path] do |_, args|
    require 'r10k/puppetfile'
    require 'puppet_forge'
    require 'pathname'

    modpath = Pathname.new args[:path] || r10k_default_modpath
    curpath = Pathname.new Dir.pwd

    puppetfile_dir = File.expand_path(File.join(__FILE__, '..'))
    modules_dir = File.join(puppetfile_dir, modpath.relative_path_from(curpath))
    puppetfile = R10K::Puppetfile.new(puppetfile_dir, modules_dir)
    puppetfile.load!

    puts "Processing Puppetfile for fixtures"
    puppetfile.modules.each do |mod|
      if mod.status == :insync
        puts "Skipping #{mod.name} (#{mod.version}) already in sync"
      else
        if mod.status == :absent
          msg = "installed #{mod.name}"
        else
          msg = "updated #{mod.name} from #{mod.version} to"
        end
        mod.sync
        if mod.status != :insync
          puts "Failed to sync #{mod.name}".red
        else
          puts "Successfully #{msg} #{mod.version}".green
        end
      end
    end
  end

  task :spec_clean do
    require 'fileutils'

    if File.exist?(r10k_spec_modpath)
      FileUtils.remove_dir(r10k_spec_modpath)
    end
  end
end

# prepending r10k task to prep
task :spec_prep => ['r10k:spec_install']

Rake::Task[:spec_clean].enhance do
  Rake::Task['r10k:spec_clean'].invoke
end
```

If it is of interest I can submit the `:install` task via a PR

**Comment by dhollinger** [comment]
What would be the benefit of this over the `r10k deploy` command or the puppet take in `puppet-r10k`?

**Comment by electrofelix** [comment]
Where someone wants to ensure the Puppetfile is automatically processed and part of calling `rake spec` it's much easier to reference existing tasks as well as be told about what it's doing at part of the test run setup.

I don't want to have to remember to check that I'm missing some modules added to the Puppetfile after I do a git pull together sync and test my changes locally applied to the latest codebase.
