### ISSUE TITLE
Consider making r10k:install have a default path of '.'

### ISSUE THREAD

**Issue by asedge** [voxpupuli/ra10ke#25]
I want to make the new `r10k:install` task a prerequisite of another task that accepts no arguments.  I'm struggling with this because Rake doesn't appear to provide a way to define a prerequisite while passing arguments.  Would you accept a PR that sets the default for the `:path` equal to `.` or something along those lines?

**Comment by ZeroPointEnergy** [comment]
The default can now be defined when creating the tasks. See the documentation for the configuration for the new release.

I think this can be closed

**Comment by bastelfreak** [comment]
@asedge please let us know if this is still an issue for you. If so, we can reopen the issue.
