### ISSUE TITLE
rake validate error

### ISSUE THREAD

**Issue by HerveMARTIN** [voxpupuli/ra10ke#39]
With the version 0.6.0 we have an error when running :
bash -c 'source /etc/profile.d/rvm.sh && rvm use 2.3.4 && bundle exec rake validate'
Using /usr/local/rvm/gems/ruby-2.3.4
---> syntax:manifests
Current textdomain ("master_domain") was not added, use FastGettext.add_text_domain !
Current textdomain ("master_domain") was not added, use FastGettext.add_text_domain !
Current textdomain ("master_domain") was not added, use FastGettext.add_text_domain !
Current textdomain ("master_domain") was not added, use FastGettext.add_text_domain !
Current textdomain ("master_domain") was not added, use FastGettext.add_text_domain !
script returned exit code 1

**Comment by HerveMARTIN** [comment]
Still present with 0.6.2...

**Comment by waldiTM** [comment]
This happens because `Puppet::Environment` and `GettextSetup` (used by `R10K`) are fighting over the available textdomains within the `FastGettext` module. `Puppet::Environment` will clean out everything it does not know.

Workaround in `Rakefile`:
```ruby
Puppet[:disable_i18n] = true
```

**Comment by HerveMARTIN** [comment]
Thanks a lot it's working
