### ISSUE TITLE
validate task fails when repo does not exist

### ISSUE THREAD

**Issue by logicminds** [voxpupuli/ra10ke#52]
When validating on windows the rake task fails to finish when a repo does not exist. 

What should have happen is the task should have continued and marked that repo as missing.

**Comment by bastelfreak** [comment]
hey @logicminds. Sadly I'm not really a windows guy :( Any chance you can provide a PR for this?

**Comment by logicminds** [comment]
Not even sure it is a windows issue, but I was merely documented for myself to do later.  ;)
