### ISSUE TITLE
Allow numeric tags (without leading "v")

### ISSUE THREAD

**Issue by HerveMARTIN** [voxpupuli/ra10ke#7]
As i don't find any good reason to not allow numeric tags, it would be a good thing to change this behavior.
It's sometimes difficult (or impossible) to ask third party module to change their tag naming convention...
Here is an example : https://github.com/elastic/puppet-kibana/tags

**Comment by HerveMARTIN** [comment]
I understand that the naming convention must be coherent in order to sort tags, but I think if the ref doesn't match /^[vV]\d/ you could try to match the numeric only convention, no?

**Comment by HerveMARTIN** [comment]
I'm not a ruby dev but I've made a PR : https://github.com/voxpupuli/ra10ke/pull/8

**Comment by tampakrap** [comment]
merged, thanks a lot for your work!
